src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use App\traits\TimeStampTrait;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
#[ORM\HasLifecycleCallbacks()]
class Order
{
    use TimeStampTrait;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $status = null;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $booking_date = null;

    #[ORM\Column(nullable: true)]
    private ?float $amount = null;

    #[ORM\ManyToOne(inversedBy: 'orderr')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Service $service = null;

    #[ORM\Column(length: 50)]
    private ?string $payment_method = null;
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getBookingDate(): ?\DateTimeInterface
    {
        return $this->booking_date;
    }

    public function setBookingDate(?\DateTimeInterface $booking_date): static
    {
        $this->booking_date = $booking_date;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(?float $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->service;
    }

    public function setService(?Service $service): static
    {
        $this->service = $service;

        return $this;
    }

    public function getPaymentMethod(): ?string
    {
        return $this->payment_method;
    }

    public function setPaymentMethod(string $payment_method): static
    {
        $this->payment_method = $payment_method;

        return $this;
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Entity\Service;
use App\Form\OrderType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Attribute\Route;
use DateTime;
use function Webmozart\Assert\Tests\StaticAnalysis\lower;

class ReservationController extends AbstractController
{
    #[Route('/reservation/{service_id}', name: 'add.reservation')]
    public function AddReservation($service_id,ManagerRegistry $doctrine,
                                   Request $request,Security $security,
    MailerInterface $mailer): Response
    {
        $order=new Order();
        $service=$doctrine->getRepository(Service::class)->find($service_id);
        $form=$this->createForm(OrderType::class,$order);
        $form->remove('createdAt');
        $form->remove('user');
        $form->remove('status');
        $form->remove('service');
        $form->remove('amount');
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $order->setUser($security->getUser());
            $order->setService($service);
            $order->setAmount($service->getPrice());
            $order->setStatus('pending');
            $available=false;
            $bookingDate = $order->getBookingDate();
            if ($bookingDate instanceof DateTime) {
                foreach ($service->getAvailability() as $day => $val) {
                    if ($val['unavailable']==false) {
                        $morningTime = DateTime::createFromFormat('H:i:s', $val['morning']);
                        $afternoonTime = DateTime::createFromFormat('H:i:s', $val['afternoon']);
                        if ($morningTime !== false && $afternoonTime !== false) {
                            if ($bookingDate->format('l') === ucfirst(strtolower($day)) &&
                                $bookingDate->format('H:i') >= $morningTime->format('H:i') &&
                                $bookingDate->format('H:i') < $afternoonTime->format('H:i')) {

                                $available = true;
                                break;
                            }
                        } else {
                            throw new \Exception("Invalid time format for $day: morning = {$val['morning']}, afternoon = {$val['afternoon']}");
                        }
                    }
                }
            }
            if(!$available){
                $form->get('booking_date')->addError(new FormError('This service is not available for the selected date.'));
            }else {
                $manager = $doctrine->getManager();
                $manager->persist($order);
                $manager->flush();
                $email = (new Email())
                    ->from('mohamedhabibhajjej@gmail.com')
                    ->to('mhdriabi2013@gmail.com')
                    ->subject('Test d\'envoi depuis le contrôleur')
                    ->text('Ceci est un test d\'envoi d\'email depuis un contrôleur Symfony.');
                    $mailer->send($email);
            }
        }
        return $this->render('reservation/index.html.twig', [
            'form'=>$form->createView(),
             'service'=>$service,
        ]);
    }
}

templates/reservation/index.html.twig
{% extends 'template.html.twig' %}
{% block title %}
    Reservation
{% endblock %}
{% block header %}
    <header id="head" class="secondary"></header>
{% endblock %}
{% block body %}
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Reservation</li>
        </ol>
        <div class="row justify-content-center w-100">

            <!-- Form Column -->
            <div class="col-xl-5 col-lg-6 col-md-8">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-5">
                        <!-- Form Heading -->
                        <div class="text-center mb-4">
                            <h1 class="h4 text-gray-900">Book Now</h1>
                        </div>

                        <!-- Form Start -->
                        {{ form_start(form, {'attr': {'class':'user'}}) }}

                        <!-- Name Field -->
                        <div class="form-group mb-3">
                            <label for="">Service</label>
                            <input type="text" value="{{ service.title}}" class="form-control w-100" style="border-radius: 5px;" disabled>
                        </div>
                        <div class="form-group mb-3">
                            <label for="">Location</label>
                            <input type="text" value="{{ service.location}}" class="form-control w-100" style="border-radius: 5px;" disabled>
                        </div>
                        <div class="form-group mb-3">
                            {{ form_label(form.booking_date, 'Booking Date') }}
                            {{ form_widget(form.booking_date, {'attr': {'class':'form-control w-100', 'style': 'border-radius: 5px;'}}) }}
                            {{ form_errors(form.booking_date) }}
                        </div>

                        <!-- Description Field -->
                        <div class="form-group mb-3">
                            {{ form_label(form.paymentMethod, 'Payment Method') }}
                            {{ form_widget(form.paymentMethod, {'attr': {'class':'form-control w-100', 'style': 'border-radius: 5px;'}}) }}
                            {{ form_errors(form.paymentMethod) }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="">Total</label>
                            <input type="text" value="{{ service.price }} TND" class="form-control w-100" style="border-radius: 5px;" disabled>
                        </div>

                        <!-- Submit Button -->
                        <div class="form-group">
                            <input type="submit" value="Book" class="btn btn-primary btn-user btn-block" style="border-radius: 5px;">
                        </div>

                        {{ form_end(form) }}
                        <!-- Form End -->
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}